# Generated by Django 5.2.7 on 2025-10-24 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('PL', 'Projeto de Lei Ordinária'), ('PLC', 'Projeto de Lei Complementar'), ('PEC', 'Proposta de Emenda à Lei Orgânica'), ('REQ', 'Requerimento')], default='PL', max_length=10)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('PREPARACAO', 'Em Preparação/Pauta'), ('ABERTO', 'Aberto para Votação'), ('FECHADO', 'Votação Encerrada')], default='PREPARACAO', max_length=20)),
                ('quorum_minimo', models.CharField(choices=[('SIMPLES', 'Maioria Simples (PL, REQ)'), ('ABSOLUTA', 'Maioria Absoluta (PLC)'), ('DOIS_TERCOS', '2/3 dos Vereadores (PEC)')], default='SIMPLES', max_length=20)),
                ('tempo_limite_segundos', models.IntegerField(default=60)),
                ('abertura_voto', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Projeto de Lei',
                'verbose_name_plural': 'Projetos de Lei',
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('ABSTER', 'Abstenção')], max_length=10)),
                ('data_voto', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislativo.projeto')),
                ('vereador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto de Vereador',
                'verbose_name_plural': 'Votos de Vereadores',
                'unique_together': {('projeto', 'vereador')},
            },
        ),
    ]
