# Generated by Django 5.2.7 on 2025-10-24 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('legislativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('peso_voto', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Cargo na Mesa Diretora',
                'verbose_name_plural': 'Cargos na Mesa Diretora',
            },
        ),
        migrations.CreateModel(
            name='VereadorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome_completo', models.CharField(max_length=255)),
                ('apelido_parlamentar', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cargo_mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislativo.cargo', verbose_name='Cargo na Mesa')),
            ],
            options={
                'verbose_name': 'Perfil do Vereador',
                'verbose_name_plural': 'Perfis dos Vereadores',
            },
        ),
    ]
