# Generated by Django 5.2.7 on 2025-10-29 01:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislativo', '0002_cargo_vereadorprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_vereadores', models.IntegerField(default=15, verbose_name='Limite Máximo de Vereadores')),
                ('ata_lei_organica', models.FileField(blank=True, null=True, upload_to='documentos/ata_lei_organica/', verbose_name='Ata da Lei Orgânica (PDF)')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='autor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autor do Projeto'),
        ),
        migrations.AddField(
            model_name='vereadorprofile',
            name='ata_posse',
            field=models.FileField(blank=True, null=True, upload_to='vereadores/atas/', verbose_name='Ata de Posse (PDF)'),
        ),
        migrations.AddField(
            model_name='vereadorprofile',
            name='ausente_na_sessao',
            field=models.BooleanField(default=False, verbose_name='Ausente na Sessão Atual'),
        ),
        migrations.AddField(
            model_name='vereadorprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='vereadores/fotos/'),
        ),
        migrations.AddField(
            model_name='vereadorprofile',
            name='nome_candidatura',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome de Candidatura'),
        ),
        migrations.AddField(
            model_name='vereadorprofile',
            name='partido',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('PREPARACAO', 'Em Preparação'), ('EM_PAUTA', 'Em Pauta'), ('ABERTO', 'Aberto para Votação'), ('FECHADO', 'Votação Encerrada')], default='PREPARACAO', max_length=20),
        ),
        migrations.AlterField(
            model_name='vereadorprofile',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Em Exercício'),
        ),
        migrations.CreateModel(
            name='TokenAtivacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('expira_em', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
