# Generated by Django 5.2.7 on 2025-10-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislativo', '0003_configuracao_projeto_autor_vereadorprofile_ata_posse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='limite_vereadores',
            field=models.IntegerField(default=9, verbose_name='Limite Máximo de Vereadores'),
        ),
    ]
