# Generated by Django 5.2.7 on 2025-11-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislativo', '0004_alter_configuracao_limite_vereadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='resultado_final',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('EMPATADO', 'Empatado'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=20, verbose_name='Resultado Final'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tempo_limite_segundos',
            field=models.IntegerField(default=600),
        ),
    ]
